# Generated by Django 6.0.6 on 2026-06-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0002_rename_creadential_credential"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="credential",
            name="password",
        ),
        migrations.AddField(
            model_name="credential",
            name="encrypted_password",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
    ]
